config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :users, only: [:index, :create]
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#facebook'
  get '/most_popular' => 'locations#popular'
  get '/calendars/:calendar_name/events/:id/next' => 'events#next'
  get '/calendars/:calendar_name/events/:id/prev' => 'events#prev'
  get '/locations/:id/next' => 'locations#next'
  get '/locations/:id/prev' => 'locations#prev'
  resources :calendars, param: :name do
    resources :events
  end
  resources :locations, only: [:index, :show]
  resources :events do
    resources :comments
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one :calendar, dependent: :destroy
  has_many :invites, dependent: :destroy
  has_many :events, through: :invites
  has_many :comments

  has_secure_password
  validates :username, presence: true
  validates :username, uniqueness: true
  validates :email, presence: true
  validates :email, uniqueness: true

  def sort_by_date
    self.calendar.events.sort { |a, b| a.start_time.to_date <=> b.start_time.to_date }
  end

  def today_events
    events = self.calendar.events.select { |event| event.start_time.to_date == Date.today }
    events.sort { |a, b| a.start_time <=> b.start_time }
  end

  def next(event)
    events = self.calendar.events.select { |day| day.start_time.to_date  == event.start_time.to_date}
    sorted_events = events.sort { |a, b| a.start_time <=> b.start_time }
    next_event = sorted_events.select { |e| e.start_time > event.start_time }.first
    next_event ||= sorted_events.first

  end

  def prev(event)
    events = self.calendar.events.select { |day| day.start_time.to_date  == event.start_time.to_date}
    sorted_events = events.sort { |a, b| a.start_time <=> b.start_time }
    prev_event = sorted_events.select { |e| e.start_time < event.start_time }.last
    prev_event ||= sorted_events.last
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @events_today = current_user.today_events
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      @calendar = @user.create_calendar(name: @user.username)
      redirect_to users_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<div id="sign-index">
  <h1>Welcome <%= current_user.username.capitalize %></h1>
  <h3> <%= Date.today.strftime("%B %d, %Y") %></h3><br>
  <h3>Today's events</h3>
  <% @events_today.each do |event| %>
    <%= event.start_time.strftime("%I:%M%p") %>: <%= link_to event.title, calendar_event_path(current_user.calendar.name, event) %><br>
  <% end %>
  <br>
  <%= link_to "Today's locations", locations_path, class: "today_locations btn btn-primary btn-xs" %>
</div>

app/views/users/new.html.erb
<div id="signup" class="row justify-content-md-center">
<h1 id="sign">Sign Up</h1>
<br>
  <%= form_for @user do |f| %>
  <%= render partial: "layouts/errors", locals: { data: @user } %>
    <div class="field">
      <%= f.label :username %>
      <%= f.text_field :username, class: "form-control" %>
    </div>
    <div class="field">
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control" %>
    </div>
    <div class="field">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
    <br>
    <div class="actions">
      <%= f.submit "Sign Up", class: "btn btn-primary btn-xs"%>
    </div>
  <% end %>
</div>