config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :users, only: [:index, :create]
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#facebook'
  get '/most_popular' => 'locations#popular'
  get '/calendars/:calendar_name/events/:id/next' => 'events#next'
  get '/calendars/:calendar_name/events/:id/prev' => 'events#prev'
  get '/locations/:id/next' => 'locations#next'
  get '/locations/:id/prev' => 'locations#prev'
  resources :calendars, param: :name do
    resources :events
  end
  resources :locations, only: [:index, :show]
  resources :events do
    resources :comments
  end
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :location
  has_many :notifications, dependent: :destroy
  has_many :calendars, through: :notifications
  has_many :invites, dependent: :destroy
  has_many :users, through: :invites
  has_many :comments

  validates :title, presence: true
  validate :end_time_is_after_start_time

  def location_attributes=(location_attributes)
    if location_id != nil
      location = Location.find_by(id: location_id)
      self.location = location
    else
      self.create_location(name: location_attributes[:name], street_address: location_attributes[:street_address], city: location_attributes[:city], state: location_attributes[:state], zipcode: location_attributes[:zipcode])
    end
  end

  def add_date_value
    self.update_attribute(:date, self.start_time)
  end

  def update_creator(name)
    self.update_attribute(:creator, name)
  end

  def add_attribute_values(name)
    add_date_value
    update_creator(name)
  end

  def find_user
    users = User.find(self.user_ids)
  end

  def get_usernames
    find_user.map { |user| user.username }.join(", ")
  end

  def add_to_calendars
    find_user.each do |user|
      user.calendar.events << self
    end
  end

  def add_to_new_calendars
    find_user.each do |user|
      user.calendar.events << self unless user.calendar.events.include?(self)
    end
  end

  private

  def end_time_is_after_start_time
    if end_time < start_time
      errors.add(:end_time, "cannot be before start date/time")
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :next, :prev, :edit, :update, :destroy]
  before_action :set_calendar, only: [:index, :show, :edit, :new, :create, :update, :destroy]

  def index
    @events = current_user.sort_by_date
  end

  def show
    @comment = @event.comments.build
    respond_to do |format|
      format.html
      format.json {render json: @event}
    end
  end

  def new
    @event = Event.new
    @location = @event.build_location
  end

  def next
    @next_event = current_user.next(@event)
    render json: @next_event
  end

  def prev
    @prev_event = current_user.prev(@event)
    render json: @prev_event
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      @event.add_attribute_values(current_user.username)
      @calendar.events << @event
      @event.add_to_calendars
      redirect_to calendar_event_path(@calendar.name, @event)
    else
      render :new
    end
  end

  def update
    if @event.update(event_params)
      @event.add_date_value
      @event.add_to_new_calendars
      redirect_to calendar_event_path(@calendar.name, @event)
    else
      render :edit
    end
  end

  def destroy
    if @event.creator == current_user.username
      @event.destroy
      redirect_to calendar_events_path(@calendar.name)
    else
      @calendar.events.delete(@event)
      redirect_to calendar_events_path(@calendar.name)
    end
  end

  private

  def set_event
    @event = Event.find(params[:id])
  end

  def set_calendar
    @calendar = current_user.calendar
  end

  def event_params
    params.require(:event).permit(:title, :note, :date, :start_time, :end_time, :creator, :location_id, location_attributes: [:id, :name, :street_address, :city, :state, :zipcode, :longitude, :latitude], user_ids: [])
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for [@calendar, @event] do |f| %>
<%= render partial: "layouts/errors", locals: { data: @event } %>
  <div class="form-row">
    <div class="form-group col-md-6">
      <%= f.label :title %><br>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="form-group col-md-6">
      <%= f.label :note %><br>
      <%= f.text_field :note, class: "form-control" %>
    </div>
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <%= f.label :start_time %><br>
      <%= f.datetime_select :start_time, class: "form-control" %>
    </div>
    <div class="form-group col-md-6">
      <%= f.label :end_time %><br>
      <%= f.datetime_select :end_time, class: "form-control" %>
    </div>
  </div>
  <br>
  <h5>Pick a Location</h5>
  <%= f.collection_select :location_id, Location.all, :id, :name, include_blank: "" %>
  <br><br>
  <h5>or Create a New Location</h5>
  <%= f.fields_for :location do |loc| %>
    <div class="form-group">
      <%= loc.label :name %>
      <%= loc.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= loc.label :street_address %>
      <%= loc.text_field :street_address, class: "form-control" %>
    </div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <%= loc.label :city %>
        <%= loc.text_field :city, class: "form-control" %>
      </div>
    <div class="form-group col-md-4">
      <%= loc.label :state %>
      <%= loc.text_field :state, class: "form-control" %>
    </div>
    <div class="form-group col-md-2">
      <%= loc.label :zipcode %>
      <%= loc.text_field :zipcode, class: "form-control" %>
    </div>
  </div>
  <% end %>
  <br>

  <h5>Notify event to others: <%= f.collection_check_boxes :user_ids, User.where.not(id: current_user.id), :id, :username %></h5>

  <%= f.submit "Submit", class: "btn btn-primary btn-xs" %>
<% end %>

app/views/events/edit.html.erb
<div class="event-form">
  <h1>Edit event</h1><br>
  <%= render 'form' %>
</div>

app/views/events/index.html.erb
<div class="event">
  <h1><%= current_user.username.capitalize %>'s Events</h1>
  <br>
  <%= month_calendar events: @events do |date, events| %>
    <%= date.day %>
    <% events.each do |event| %>
      <div>
        <%= link_to event.title, calendar_event_path(@calendar.name, event) %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/events/new.html.erb
<div class="event-form">
  <h1>Create event</h1><br>
  <%= render 'form' %>
</div>

app/views/events/show.html.erb
<div class="event-show">
  <div class="show">
    <h1><%= @event.title %></h1>
    <p>Date: <%= @event.date.strftime("%b %d, %Y") %></p>
    <p>Start Time: <%= @event.start_time.strftime("%I:%M%p") %></p>
    <p>End Time: <%= @event.end_time.strftime("%I:%M%p") %></p>
    <% if @event.note != "" %>
    <p>Note: <%= @event.note %></p>
    <% end %>
    <p>Location: <%= @event.location.name %></p>
    <p>Address: <%= @event.location.street_address %> <%= @event.location.city %> <%= @event.location.state %> <%= @event.location.zipcode %><p>
    <p>Creator: <%= @event.creator %></p>
    <p>Notified: <%= @event.get_usernames %></p>
  </div>

  <div>
    <% if @event.creator == @calendar.name %>
      <%= link_to "Edit", edit_calendar_event_path(@calendar.name, @event) %> |
    <% end %>

    <%= link_to 'Delete', calendar_event_path(@calendar.name, @event), method: :delete, data: {confirm: 'Are you sure?'} %>
  </div>
</div>
<br>

<div class="comment-form">
  <h3>Add comment</h3>
  <%= form_for [@event, @comment] do |f| %>
  <%= f.text_area :content, size: "60x2", placeholder: "Write a comment..." %><br>
  <%= f.submit "Submit", class: "btn btn-outline-primary"%>
  <% end %>
</div>
<br>

<button id="prev" class="prev-event btn btn-outline-primary" data-id="<%= @event.id %>">Previous Event</button>
<%= link_to 'Comments', event_comments_path(@event), id: "commments-button", class: "all-comments btn btn-outline-primary" %>
<button id="next" class="next-event btn btn-outline-primary" data-id="<%= @event.id %>">Next Event</button><br><br>

<div class="comments">
</div>