config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :users, only: [:index, :create]
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#facebook'
  get '/most_popular' => 'locations#popular'
  get '/calendars/:calendar_name/events/:id/next' => 'events#next'
  get '/calendars/:calendar_name/events/:id/prev' => 'events#prev'
  get '/locations/:id/next' => 'locations#next'
  get '/locations/:id/prev' => 'locations#prev'
  resources :calendars, param: :name do
    resources :events
  end
  resources :locations, only: [:index, :show]
  resources :events do
    resources :comments
  end
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :events, dependent: :destroy

  validates :name, presence: true
  validates :street_address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zipcode, presence: true

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  def address
    [street_address, city, state, zipcode].join(", ")
  end

  def address_changed?
    street_address_changed? || city_changed? || state_changed? || zipcode_changed?
  end

  def self.most_popular
    joins(:events).group(:id).having("COUNT(*) > 1").order("COUNT(*) DESC").limit(5)
  end

  def next
    locations = Location.most_popular
    selected_loc = locations.select { |loc| loc.events.length == self.events.length && loc.id > self.id }
    if selected_loc == []
      next_location = locations.select { |loc| loc.events.length < self.events.length }.first
    else
      next_location = selected_loc.first
    end
    next_location ||= locations.first
  end

  def prev
    locations = Location.most_popular
    selected_loc = locations.select { |loc| loc.events.length == self.events.length && loc.id < self.id }
    if selected_loc == []
      prev_location = locations.select { |loc| loc.events.length > self.events.length }.last
    else
      prev_location = selected_loc.last
    end
    prev_location ||= locations.last
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :next, :prev]

  def index
    @user_locations = current_user.today_events
  end

  def show
    respond_to do |format|
      format.html
      format.json {render json: @location}
    end
  end

  def next
    @next_location = @location.next
    render json: @next_location
  end

  def prev
    @prev_location = @location.prev
    render json: @prev_location
  end

  def popular
    @locations = Location.most_popular
    respond_to do |format|
      format.html
      format.json {render json: @locations}
    end
  end

  private

  def set_location
    @location = Location.find(params[:id])
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/index.html.erb
<div class="location">
  <h1>Places to go today</h1>
  <% @user_locations.each do |event| %>
    <div class="event-loc">
      <%= event.start_time.strftime("%I:%M%p") %><br>
      Location: <%= event.location.name %><br>
      Address: <%= event.location.street_address %> <%= event.location.city %> <%= event.location.state %> <%= event.location.zipcode %>
    </div><br>
  <% end %>
</div>
<br>

app/views/locations/popular.html.erb
<div class="location">
  <h2>Most Popular Locations</h2>
  <div class="loc">
  <ol>
    <% @locations.each do |location| %>
    <li class="popular"><%=link_to location.name, location_path(location) %></li>
    <% end %>
  </ol>
  </div>
</div>

app/views/locations/show.html.erb
<div class="location">
  <h1><%= @location.name %></h1>
  <p class="show">Address: <%= @location.street_address %> <%= @location.city %> <%= @location.state %> <%= @location.zipcode %><p>
</div>