config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  resources :users, only: [:index, :create]
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#facebook'
  get '/most_popular' => 'locations#popular'
  get '/calendars/:calendar_name/events/:id/next' => 'events#next'
  get '/calendars/:calendar_name/events/:id/prev' => 'events#prev'
  get '/locations/:id/next' => 'locations#next'
  get '/locations/:id/prev' => 'locations#prev'
  resources :calendars, param: :name do
    resources :events
  end
  resources :locations, only: [:index, :show]
  resources :events do
    resources :comments
  end
end

app/views/layouts/_errors.html.erb
<% if data.errors.any? %>
  <div id="error_explanation">
    <h3 id="error"><%= pluralize(data.errors.count, "error") %></h3>
    <% data.errors.full_messages.each do |message| %>
      <%= message %><br>
    <% end %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav>
  <ul class="nav justify-content-end">
  <% if logged_in? %>
    <li class="nav-item link"><%= link_to "Home", users_path, class: "nav-link btn btn-sm align-middle btn-outline-primary" %></li>
    <li class="nav-item link"><%= link_to "Calendar", calendar_events_path(current_user.username), class: "nav-link btn btn-sm align-middle btn-outline-primary" %></li>
    <li class="nav-item link"><%= link_to "Add event", new_calendar_event_path(current_user.username), class: "nav-link btn btn-sm align-middle btn-outline-primary" %></li>
    <li class="nav-item link"><%=link_to "Most Popular Locations", most_popular_path, class: "popular-loc nav-link btn btn-sm align-middle btn-outline-primary" %></li>
    <li class="nav-item link"><%= link_to "Log out", logout_path, method: "delete", class: "nav-link btn btn-sm align-middle btn-outline-primary" %></li>
  <% else %>
    <li class="nav-item link"><%= link_to "Sign Up", signup_path, class: "nav-link btn btn-sm align-middle btn-outline-primary"%></li>
    <li class="nav-item link"><%= link_to "Log In", login_path, class: "nav-link btn btn-sm align-middle btn-outline-primary" %></li>
    <li class="nav-item link"><%= link_to "Log in with Facebook", "/auth/facebook", class: "fa fa-facebook-square nav-link" %></li>
  <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EReminder</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>

  <body class="home">
    <% if alert %>
      <div id="alert_wrapper">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
    <%= render "layouts/navbar" %>
    <div id="main" class="container text-center">
      <%= yield %>
    </div>
  </body>
</html>